
image: gradle:7.4

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle  

stages:
    - build
    - test
    - checkstyle
    - deploy

build:
  stage: build
  script: 
    - gradle assemble

test:
  stage: test
  script:
      - echo "running unit tests..."
      - gradle test
      - gradle jacocoTestCoverageVerification --info
      - gradle testCodeCoverageReport
      - cat $CI_PROJECT_DIR/build/reports/jacoco/testCodeCoverageReport/html/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - $CI_PROJECT_DIR/api/build/reports/*
      - $CI_PROJECT_DIR/domain/build/reports/*
   
checkstyle: 
  stage: checkstyle
  script:
    - gradle check
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/api/build/reports/*
      - $CI_PROJECT_DIR/domain/build/reports/*


deploy:
  stage: deploy
  rules: 
    - if: $CI_COMMIT_TAG
  script: 
    - gradle distZip
  artifacts:
    paths:
    - $CI_PROJECT_DIR/api/build/distributions/*


