
image: gradle:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle  

stages:
    - build
    - test


build-job:
  stage: build
  script: 
    - ./gradlew assemble
    - mkdir build/
    - echo "My application test file" > build/testcoverage-file-v1
  artifacts: 
    paths:
      - build/testcoverage-file-v1



test-job:
  stage: test
  script:
      - echo "running unit tests..."
      - gradle test
      - gradle jacocoTestCoverageVerification --info
      - cat $CI_PROJECT_DIR/build/testcoverage-file-v1
  